### ISSUE TITLE
Would it be possible to have an 100x player net play option?

### ISSUE THREAD

**Issue by spaced-out-mvc** [DeadHamster35/OverKart64#1]

**Comment by spaced-out-mvc** [comment]
It would be good if you could network play across lan/wan with up to 100x players

In two different modes
- 1) All players on screen with/without weapons 
- 2) All players on screen ghosted time trial mode

**Comment by kfkaplan** [comment]
Probably never.  There are a lot of issues you would need to overcome such as limited RAM size you have to work with and the crazy amount of network lag 100 players would create.  4 player N64 netplay is already pretty laggy.

**Comment by MegaMech** [comment]
Hello,

This is likely outside the scope of Tarmac64/Overkart. Eight player networking may be achieved through decomp. I recommend contributing to that repository if you would like to see your idea come to fruition.
